models/Curso.py
from database import db
from sqlalchemy import ForeignKey
from models.User import User  # Importe seu modelo User

class Curso(db.Model):
    __tablename__='cursos'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    tipo = db.Column(db.String)
    descricao = db.Column(db.String(100))
    user_id = db.Column(db.Integer, ForeignKey('users.id'), nullable=False) # Adicione o campo user_id
    
    user = db.relationship('User', backref=db.backref('cursos', lazy=True))  # Relação com a tabela User

    def __repr__(self):
        return f'<Curso id={self.id}, name={self.name}, tipo={self.email}, user_id={self.user_id}>'
        
    def toJson(self):
        return {"id": self.id, "name": self.name, "tipo": self.tipo, "descricao": self.descricao, "user_id": self.user_id}

controllers/admin_controller.py
# controllers/admin_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from functools import wraps
from models.Admin import Admin
from models.User import User
from models.Teacher import Teacher
from database import db
from werkzeug.security import generate_password_hash
from middleware import admin_required_middleware

admin_bp = Blueprint('admin', __name__, url_prefix='/admin')
    
@admin_bp.route('/')
@admin_required_middleware
def painel():
    return render_template('admin/painel.html')
# Rota para listar todos os usuários
@admin_bp.route('/users')
@admin_required_middleware
def listar_usuarios():
    users = User.query.all()
    return render_template('admin/listar_usuarios.html', users=users)
# Rota para adicionar um admin
@admin_bp.route('/add_admin', methods=['GET', 'POST'])
@admin_required_middleware
def add_admin():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        hashed_password = generate_password_hash(password)
        new_admin = Admin(name=name, email=email, senha=hashed_password)
        db.session.add(new_admin)
        db.session.commit()
        flash('Admin adicionado com sucesso!', 'success')
        return redirect(url_for('admin.listar_usuarios'))
    return render_template('admin/add_admin.html')
# Rota para excluir um professor
@admin_bp.route('/delete_teacher/<int:id>')
@admin_required_middleware
def delete_teacher(id):
    teacher = Teacher.query.get_or_404(id)
    db.session.delete(teacher)
    db.session.commit()
    flash('Professor excluido com sucesso', 'success')
    return redirect(url_for('admin.painel'))
# Rota para excluir um usuario
@admin_bp.route('/delete_user/<int:id>')
@admin_required_middleware
def delete_user(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    flash('Usuario excluido com sucesso', 'success')
    return redirect(url_for('admin.listar_usuarios'))

controllers/cursos_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from database import db
from models.Curso import Curso
from models.Comment import Comment
from models.User import User
from functools import wraps

cursos_bp = Blueprint('cursos', __name__)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('login.exibir_formulario'))
        return f(*args, **kwargs)
    return decorated_function

@cursos_bp.route('/cursos', methods=['GET', 'POST'])
def exibir_cursos():
    cursos = Curso.query.all()
    page_id = 1  # Defina o ID da página corretamente
    comments = Comment.query.filter_by(page_id=page_id).all()
    if request.method == 'POST':
        conteudo = request.form['conteudo']
        if 'user_id' in session:
            user_id = session['user_id']
            new_comment = Comment(user_id=user_id, conteudo=conteudo, page_id=page_id)  # Adiciona o page_id
            db.session.add(new_comment)
            db.session.commit()
            return redirect(url_for('cursos.exibir_cursos'))

    return render_template('cursos.html', cursos=cursos, comments=comments)

@cursos_bp.route('/add_cursos', methods=['GET', 'POST'])
@login_required
def add_curso():
    if request.method == 'POST':
        name = request.form['name']
        tipo = request.form['tipo']
        descricao = request.form['descricao']
        user_id = session['user_id']
        
        new_curso = Curso(name=name, tipo=tipo, descricao=descricao, user_id = user_id) #salva o user_id do criador
        db.session.add(new_curso)
        db.session.commit()
        return redirect(url_for('cursos.exibir_cursos'))
    return render_template('add_cursos.html')

@cursos_bp.route('/add_cursos')
@login_required
def exibir_formulario_add_curso():
    return render_template('add_cursos.html')

@cursos_bp.route('/edit_cursos/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_curso(id):
    curso = Curso.query.get_or_404(id)
    if request.method == 'POST':
       curso.name = request.form['name']
       curso.tipo = request.form['tipo']
       curso.descricao = request.form['descricao']
       db.session.commit()
       return redirect(url_for('cursos.exibir_cursos'))
    return render_template('edit_cursos.html', curso = curso)


@cursos_bp.route('/delete_cursos/<int:id>')
@login_required
def delete_curso(id):
    curso = Curso.query.get_or_404(id)
    if curso.user_id != session['user_id']: # verifica se o usuario logado é o criador
        return "Você não tem permissão para excluir este professor.", 403
    db.session.delete(curso)
    db.session.commit()
    return redirect(url_for('cursos.exibir_cursos'))

controllers/ia_controller.py
# Em controllers/ia_controller.py
from flask import Blueprint, request, jsonify
import google.generativeai as genai
import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

genai.configure(api_key=GOOGLE_API_KEY)

ia_bp = Blueprint('ia', __name__)

@ia_bp.route('/ia_response', methods=['POST'])
def ia_response():
   data = request.get_json()
   question = data.get('question')

   if question:
       try:
           model = genai.GenerativeModel('gemini-pro')
           response = model.generate_content(question)
           answer = response.text

       except Exception as e:
             answer = f"Desculpe, ocorreu um erro ao processar sua pergunta. Tente novamente mais tarde. {e}"
   else:
       answer = "Nenhuma pergunta foi feita!"
   return jsonify({'response': answer})

controllers/login_controller.py
# controllers/login_controller.py

import os
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from werkzeug.utils import secure_filename
from repository.user_repository import UserRepository
from repository.admin_repository import AdminRepository

login_bp = Blueprint('login', __name__)
user_repository = UserRepository()
admin_repository = AdminRepository()

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# controllers/login_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from werkzeug.utils import secure_filename
from repository.user_repository import UserRepository
from repository.admin_repository import AdminRepository

login_bp = Blueprint('login', __name__)
user_repository = UserRepository()
admin_repository = AdminRepository()

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@login_bp.route('/acessar_conta', methods=['GET', 'POST'])
def acessar_conta():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = user_repository.get_user_by_email(email)
        if user and user.check_password(password):
            session['user_id'] = user.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('pagina_inicial'))  # Redireciona para a home
        
        admin = admin_repository.get_admin_by_email(email)
        if admin and admin.check_password(password):
            session['user_id'] = admin.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('pagina_inicial'))  # Redireciona para a home

        flash('Email ou senha incorretos', 'danger')
        return render_template('entrar.html', error="Email ou senha incorretos")

    return render_template('entrar.html')
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = user_repository.get_user_by_email(email)
        if user and user.check_password(password):
            session['user_id'] = user.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('pagina_inicial'))  # Redireciona para a home
        
        admin = admin_repository.get_admin_by_email(email)
        if admin and admin.check_password(password):
            session['user_id'] = admin.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('admin.painel'))  # Redireciona para o painel do admin
        
        flash('Email ou senha incorretos', 'danger')
        return render_template('entrar.html', error="Email ou senha incorretos")

    return render_template('entrar.html')
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = user_repository.get_user_by_email(email)
        if user and user.check_password(password):
            session['user_id'] = user.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('pagina_inicial'))

        admin = admin_repository.get_admin_by_email(email)
        if admin and admin.check_password(password):
            session['user_id'] = admin.id
            flash('Bem-vindo de volta!', 'success')
            return redirect(url_for('admin.painel')) # Redireciona para o painel de admin

        flash('Email ou senha incorretos', 'danger')
        return render_template('entrar.html', error="Email ou senha incorretos")

    return render_template('entrar.html')


@login_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        password = request.form['password']

        if user_repository.get_user_by_email(email):
            flash('Email já cadastrado.', 'danger')
            return render_template('register.html', error="Email já cadastrado.")

        # Cadastro de admin (alterar se necessário para usuários normais)
        admin_repository.add_admin(name, email, password)

        flash('Sua conta foi criada com sucesso!', 'success')
        return redirect(url_for('login.acessar_conta'))

    return render_template('register.html')

@login_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    flash('Você saiu... LAMENTÁVEL', 'dark')
    return redirect(url_for('pagina_inicial'))

@login_bp.route('/exibir_formulario')
def exibir_formulario():
    return render_template('entrar.html')

@login_bp.route('/editar_perfil', methods=['GET', 'POST'])
def editar_perfil():
    if 'user_id' not in session:
        return redirect(url_for('login.exibir_formulario'))

    user_id = session['user_id']
    user = user_repository.get_user_by_id(user_id)
    admin = admin_repository.get_admin_by_id(user_id)

    profile_picture = (
        admin.profile_picture if admin else user.profile_picture if user else None
    )

    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']

        if 'profile_picture' in request.files:
            file = request.files['profile_picture']
            if file and file.filename != '' and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                upload_folder = 'static/uploads'
                os.makedirs(upload_folder, exist_ok=True)

                file_path = os.path.join(upload_folder, filename)
                file.save(file_path)

                if admin:
                    admin.profile_picture = f'uploads/{filename}'
                    admin_repository.update_admin(admin)
                    session['profile_picture'] = admin.profile_picture
                else:
                    user.profile_picture = f'uploads/{filename}'
                    user_repository.update_user(user)
                    session['profile_picture'] = user.profile_picture

        if admin:
            admin.name = name
            admin.email = email
            admin_repository.update_admin(admin)
        else:
            user.name = name
            user.email = email
            user_repository.update_user(user)

        return redirect(url_for('pagina_inicial'))

    return render_template('editar_perfil.html', user=user, profile_picture=profile_picture)

controllers/professores_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from database import db
from models.Teacher import Teacher
from models.Comment import Comment
from models.User import User
from functools import wraps

professores_bp = Blueprint('professores', __name__)

# Decorator para verificar se o usuário está logado
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('login.exibir_formulario'))
        return f(*args, **kwargs)
    return decorated_function

@professores_bp.route('/professores', methods=['GET', 'POST'])
def exibir_professores():
    teachers = Teacher.query.all()
    page_id = 1  # Defina o ID da página corretamente
    comments = Comment.query.filter_by(page_id=page_id).all()
    if request.method == 'POST':
        conteudo = request.form['conteudo']
        if 'user_id' in session:
            user_id = session['user_id']
            new_comment = Comment(user_id=user_id, conteudo=conteudo, page_id=page_id)  # Adiciona o page_id
            db.session.add(new_comment)
            db.session.commit()
            return redirect(url_for('professores.exibir_professores'))

    return render_template('professores.html', teachers=teachers, comments=comments)


@professores_bp.route('/add_professores', methods=['GET', 'POST'])
@login_required
def add_teacher():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        idade = request.form['idade']
        descricao = request.form['descricao']
        user_id = session['user_id']

        new_teacher = Teacher(name=name, email=email, idade=idade, descricao=descricao, user_id=user_id)  # salva o user_id do criador
        db.session.add(new_teacher)
        db.session.commit()
        return redirect(url_for('professores.exibir_professores'))
    return render_template('add_professores.html')

@professores_bp.route('/add_professores')
@login_required
def exibir_formulario_add_teacher():
    return render_template('add_professores.html')


@professores_bp.route('/edit_professores/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_teacher(id):
    teacher = Teacher.query.get_or_404(id)
    if request.method == 'POST':
        teacher.name = request.form['name']
        teacher.email = request.form['email']
        teacher.idade = request.form['idade']
        teacher.descricao = request.form['descricao']
        db.session.commit()
        return redirect(url_for('professores.exibir_professores'))
    return render_template('edit_professores.html', teacher=teacher)


@professores_bp.route('/delete_professores/<int:id>')
@login_required
def delete_teacher(id):
    teacher = Teacher.query.get_or_404(id)
    if teacher.user_id != session['user_id']:  # verifica se o usuario logado é o criador
        return "Você não tem permissão para excluir este professor.", 403
    db.session.delete(teacher)
    db.session.commit()
    return redirect(url_for('professores.exibir_professores'))

templates/add_cursos.html
<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Curso</title>
</head>
<body>
    <h1>Adicionar Novo Curso</h1>
    <form action="{{ url_for('cursos.add_curso') }}" method="POST">
        <label for="name">Nome:</label><br>
        <input type="text" id="name" name="name" required><br><br>

        <label for="tipo">Tipo:</label><br>
        <input type="tipo" id="tipo" name="tipo" required><br><br>

        <label for="descricao">Descrição:</label><br>
        <textarea id="descricao" name="descricao" required></textarea><br><br>

        <button type="submit">Adicionar</button>
    </form>

    <a href="/cursos/cursos">Voltar à lista</a>
</body>
</html>

templates/add_professores.html
<!DOCTYPE html>
<html>
<head>
    <title>Adicionar Professor</title>
</head>
<body>
    <h1>Adicionar Novo Professor</h1>
    <form action="{{ url_for('professores.add_teacher') }}" method="POST">
        <label for="name">Nome:</label><br>
        <input type="text" id="name" name="name" required><br><br>

        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br><br>

        <label for="idade">Idade:</label><br>
        <input type="number" id="idade" name="idade" required><br><br>

        <label for="descricao">Descrição:</label><br>
        <textarea id="descricao" name="descricao" required></textarea><br><br>

        <button type="submit">Adicionar</button>
    </form>

    <a href="/professores/professores">Voltar à lista</a>
</body>
</html>

templates/cursos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>
    {% extends "base.html" %}
    {% block content %}
    <header>
        <div>
            <div class="logo">
                <img src="{{ url_for('static', filename='images/images.png') }}" alt="">
            </div>
            <div class="texto">
                <h1>WIKI DO IFSP</h1>
                <p>Seja bem vindo!!!</p>
            </div>
            <div class="registrar">
                {% if 'user_id' in session %}
                <img src="{{ url_for('static', filename=session.get('profile_picture', 'images/default_profile.png')) }}"
                    alt="Foto de Perfil" style="max-width: 50px;border-radius: 50%;">

                <a href="{{ url_for('login.logout') }}">Sair</a> <br> <br>
                <a href="{{ url_for('login.editar_perfil') }}">Editar Conta</a>
                {% else %}
                <a href="{{ url_for('login.exibir_formulario') }}">Entrar</a> <br><br>
                <a href="{{ url_for('login.register') }}">Não tem conta?</a>
                {% endif %}
            </div>
        </div>
    </header>
    <h1>Cursos do IFSP</h1>
    <p>O IFSP oferece uma gama de possibilidades para quem está querendo se especializar numa área, tendo tanto cursos
        de barechado e técnico integrado</p>
    <p>Aqui você pode adicionar e editar informações sobre os cursos que conhece</p>

    <ul>
        {% for Curso in cursos %}
        <li> <b>Nome:</b> {{ Curso.name }} <br> <b>Tipo:</b> {{ Curso.tipo }} <br> <b>Descrição:</b> {{ Curso.descricao
            }} <br>
            <a href="{{ url_for('cursos.edit_curso', id=Curso.id) }}">Editar</a>
            {% if session.user_id == Curso.user_id %} <!-- Verifica se o usuário é o criador -->
            <a href="{{ url_for('cursos.delete_curso', id=Curso.id) }}">Excluir</a>
            {% endif %}
            <br><br>
        </li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('cursos.exibir_formulario_add_curso') }}">Adicionar Novo Curso</a>
    <br>

    <div>
        <h2>Comentários</h2>
        {% for comment in comments %}
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            {% if comment.user.profile_picture %}
            <img src="{{ url_for('static', filename=comment.user.profile_picture) }}" alt="Foto de Perfil"
                style="width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;">
            {% else %}
            <img src="{{ url_for('static', filename='images/default_profile.png') }}" alt="Foto de Perfil Padrão"
                style="width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;">
            {% endif %}
            <p><strong>{{ comment.user.name }}:</strong> {{ comment.conteudo }}</p>
        </div>
        {% endfor %}
        <form method="post">
            <textarea name="conteudo" rows="4" cols="50" required></textarea>
            <br>
            <button type="submit">Enviar comentário</button>
        </form>
    </div>
    <a href="/">Voltar ao Home</a> <br>
    {% endblock %}
</body>

</html>

templates/edit_professores.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Professor</title>
</head>
<body>
    <h1>Editar Professor</h1>
    <form action="{{ url_for('professores.edit_teacher', id=teacher.id) }}" method="POST">
        <label for="name">Nome:</label><br>
        <input type="text" id="name" name="name" value="{{ teacher.name }}" required><br><br>

        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" value="{{ teacher.email }}" required><br><br>

        <label for="idade">Idade:</label><br>
        <input type="number" id="idade" name="idade" value="{{ teacher.idade }}" required><br><br>

        <label for="descricao">Descrição:</label><br>
        <textarea id="descricao" name="descricao" required>{{ teacher.descricao }}</textarea><br><br>

        <button type="submit">Salvar</button>
    </form>

    <a href="/professores/professores">Voltar à lista</a>
</body>
</html>

templates/editar_perfil.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Perfil</title>
</head>
<body>
    <h1>Editar Perfil</h1>
    <form method="POST" action="{{ url_for('login.editar_perfil') }}" enctype="multipart/form-data">
        <label for="name">Nome:</label><br>
        <input type="text" id="name" name="name" value="{{ user.name }}" required><br><br>

        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" value="{{ user.email }}" required><br><br>

        <label for="profile_picture">Foto de Perfil:</label><br>
        <input type="file" id="profile_picture" name="profile_picture"><br><br>

        <button type="submit">Salvar</button>
    </form>
    <br>
    {% if user.profile_picture %}
        <img src="{{ url_for('static', filename=user.profile_picture) }}" alt="Foto de Perfil" style="max-width: 100px;">
    {% endif %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
</head>

<body>
    {% extends "base.html" %}
    {% block content %}
    <header>
        <div>
            <div class="logo">
                <img src="{{ url_for('static', filename='images/images.png') }}" alt="">
            </div>
            <div class="texto">
                <h1>WIKI DO IFSP</h1>
                <p>Seja bem vindo!!!</p>
            </div>
            <div class="registrar">
                {% if 'user_id' in session %}
                <img src="{{ url_for('static', filename=session.get('profile_picture', 'images/default_profile.png')) }}"
                    alt="Foto de Perfil" style="max-width: 50px;border-radius: 50%;">

                <a href="{{ url_for('login.logout') }}">Sair</a> <br> <br>
                <a href="{{ url_for('login.editar_perfil') }}">Editar Conta</a>
                {% else %}
                <a href="{{ url_for('login.exibir_formulario') }}">Entrar</a> <br> <br>
                <a href="{{ url_for('login.register') }}">Não tem conta?</a>
                {% endif %}
            </div>
    </header>

    <br><br><br>
    <a href="/professores/professores">Ver professores</a> <br>
    <a href="/cursos/cursos">Cursos Oferecidos no IFSP</a> <br>
    <a href="https://drive.google.com/drive/folders/12LMVbcRsE61cpPIc8XaqZRs0xmz0d4J6?usp=sharing">Materiais de
        Estudo</a> <br>
    <a href="https://www.ifsp.edu.br/">Site Oficial da Escola</a>
    <a href="/ia">Converse com nossa Inteligência Artificial</a>

    <center>
        <div class="container">
            <h2>Quem Somos?</h2>
            <p>Somos um grupo de estudantes do Instituto Federal de Educação, Ciência e Tecnologia de São Paulo (IFSP),
                unidos pelo objetivo de compartilhar conhecimento, experiências e recursos que enriquecem nossa jornada
                acadêmica
                e pessoal.</p>

            <p>Esta wiki é um espaço colaborativo criado por e para os alunos, onde reunimos informações úteis sobre a
                vida no IFSP,
                como materiais de estudo, dicas para projetos, eventos, histórias e tudo mais que fortaleça nossa
                comunidade.</p>

            <p>Acreditamos no poder da troca de conhecimentos e no impacto positivo que podemos gerar quando trabalhamos
                juntos.
                Nossa diversidade de cursos, campi e interesses é nossa maior força, e essa plataforma reflete a riqueza
                de ideias
                e talentos que temos entre nós.</p>
            </br>
            <h3>Nosso Objetivo</h3>
            <ul>
                <li>Facilitar o acesso a informações importantes para os estudantes;</li>
                <li>Incentivar a colaboração e a troca de experiências;</li>
                <li>Criar um ambiente acolhedor e inclusivo para todos os alunos do IFSP.</li>
            </ul>

            <p>Esta wiki é um reflexo do espírito coletivo que nos une como estudantes do IFSP. Se você também quer
                contribuir,
                junte-se a nós e faça parte dessa construção!</p>
        </div>
    </center>
    {% endblock %}
</body>

</html>

templates/professores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Professores</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
    <header>
        <div>
            <div class="logo">
                <img src="{{ url_for('static', filename='images/images.png') }}" alt="">
            </div>
            <div class="texto">
                <h1>WIKI DO IFSP</h1>
                <p>Seja bem vindo!!!</p>
            </div>
            <div class="registrar">
                {% if 'user_id' in session %}
                    <img src="{{ url_for('static', filename=session.get('profile_picture', 'images/default_profile.png')) }}" alt="Foto de Perfil" style="max-width: 50px;border-radius: 50%;">

                    <a href="{{ url_for('login.logout') }}">Sair</a> <br> <br>
                    <a href="{{ url_for('login.editar_perfil') }}">Editar Conta</a>
                {% else %}
                <a href="{{ url_for('login.exibir_formulario') }}">Entrar</a> <br><br>
                <a href="{{ url_for('login.register') }}">Não tem conta?</a>
                {% endif %}
            </div>
        </div>
    </header>
    <h1>Professores</h1>
    <ul>
        {% for Teacher in teachers %}
            <li>
                <b>Nome:</b> {{ Teacher.name }} <br>
                <b>Email:</b> {{ Teacher.email }} <br>
                <b>Idade:</b> {{ Teacher.idade }} <br>
                <b>Descrição:</b> {{ Teacher.descricao }} <br>
                <a href="{{ url_for('professores.edit_teacher', id=Teacher.id) }}">Editar</a>
                {% if session.user_id == Teacher.user_id %}  <!-- Verifica se o usuário é o criador -->
                    <a href="{{ url_for('professores.delete_teacher', id=Teacher.id) }}">Excluir</a>
                {% endif %}
                <br><br>
            </li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('professores.exibir_formulario_add_teacher') }}">Adicionar Novo Professor</a>
    <br><br>
    <div>
        <h2>Comentários</h2>
        {% for comment in comments %}
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            {% if comment.user.profile_picture %}
            <img src="{{ url_for('static', filename=comment.user.profile_picture) }}" alt="Foto de Perfil" style="width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;">
            {% else %}
            <img src="{{ url_for('static', filename='images/default_profile.png') }}" alt="Foto de Perfil Padrão" style="width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;">
            {% endif %}
            <p><strong>{{ comment.user.name }}:</strong> {{ comment.conteudo }}</p>
        </div>
        {% endfor %}
        <form method="post">
            <textarea name="conteudo" rows="4" cols="50" required></textarea>
            <br>
            <button type="submit">Enviar comentário</button>
        </form>
    </div>
    <a href="/">Voltar ao Home</a>
    <br>
    {% endblock %}

    <tbody>
        {% for teacher in teachers %}
           <tr>
             <td>{{ teacher.id }}</td>
             <td>{{ teacher.name }}</td>
             <td>{{ teacher.email }}</td>
             <td>{{ teacher.idade }}</td>
             <td>{{ teacher.descricao }}</td>
               {% if 'user_id' in session and teacher.user_id == session['user_id'] or  'user_id' in session and admin %}
                   <td>
                       <a class="btn btn-primary" href="{{ url_for('professores.edit_teacher', id=teacher.id) }}">Editar</a>
                       <a class="btn btn-danger" href="{{ url_for('professores.delete_teacher', id=teacher.id) }}">Excluir</a>
                       <!-- Se o usuário for um admin -->
                            <a class="btn btn-danger" href="{{ url_for('admin.delete_teacher', id=teacher.id) }}">Excluir(Admin)</a>
                   </td>
               {% endif %}
           </tr>
           {% endfor %}
       </tbody>
</body>
</html>